xmllint --noout --schema XMLSchema.xsd ../XMLSchema/archive.xsd
xmllint --noout --schema XMLSchema.xsd ../XMLSchema/comparative.xsd
xmllint --noout --schema XMLSchema.xsd ../XMLSchema/conceptualcomponent.xsd
xmllint --noout --schema XMLSchema.xsd ../XMLSchema/datacollection.xsd
xmllint --noout --schema XMLSchema.xsd ../XMLSchema/dataset.xsd
xmllint --noout --schema XMLSchema.xsd ../XMLSchema/dcmitype.xsd
xmllint --noout --schema XMLSchema.xsd ../XMLSchema/dcterms.xsd
xmllint --noout --schema XMLSchema.xsd ../XMLSchema/dc.xsd
xmllint --noout --schema XMLSchema.xsd ../XMLSchema/ddiprofile.xsd
xmllint --noout --schema XMLSchema.xsd ../XMLSchema/ddi-xhtml11-model-1.xsd
xmllint --noout --schema XMLSchema.xsd ../XMLSchema/ddi-xhtml11-modules-1.xsd
xmllint --noout --schema XMLSchema.xsd ../XMLSchema/ddi-xhtml11.xsd
xmllint --noout --schema XMLSchema.xsd ../XMLSchema/group.xsd
xmllint --noout --schema XMLSchema.xsd ../XMLSchema/instance.xsd
xmllint --noout --schema XMLSchema.xsd ../XMLSchema/logicalproduct.xsd
xmllint --noout --schema XMLSchema.xsd ../XMLSchema/physicaldataproduct_ncube_inline.xsd
xmllint --noout --schema XMLSchema.xsd ../XMLSchema/physicaldataproduct_ncube_normal.xsd
xmllint --noout --schema XMLSchema.xsd ../XMLSchema/physicaldataproduct_ncube_tabular.xsd
xmllint --noout --schema XMLSchema.xsd ../XMLSchema/physicaldataproduct_proprietary.xsd
xmllint --noout --schema XMLSchema.xsd ../XMLSchema/physicaldataproduct.xsd
xmllint --noout --schema XMLSchema.xsd ../XMLSchema/physicalinstance.xsd
xmllint --noout --schema XMLSchema.xsd ../XMLSchema/reusable.xsd
xmllint --noout --schema XMLSchema.xsd ../XMLSchema/studyunit.xsd
xmllint --noout --schema XMLSchema.xsd ../XMLSchema/xml.xsd
